"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=lambda v: [h.strip() for h in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Aplicación Crispy Forms
    'crispy_forms',
    'crispy_bootstrap5',
    # Login rate limiting
    'axes',
    # Autenticación de dos factores (TOTP) y códigos de respaldo: los plugins
    # otp_totp y otp_static incluyen sus propios modelos (TOTPDevice;
    # StaticDevice/StaticToken) y sus migraciones.
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # Aplicación del Proyecto "app_quimico" agregada
    'app_quimico',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# django-axes must run before the default ModelBackend so repeated failures
# are counted and blocked.
# django-otp does not ship an authentication backend: the second factor is
# resolved through OTPMiddleware + django_otp.login(), so this list is kept
# unchanged.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-otp debe ir inmediatamente después de AuthenticationMiddleware:
    # decora request.user con la verificación OTP (is_verified / otp_device).
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Política Force-MFA (grupo 'Administradores'): bloquea la navegación con
    # sesión autenticada y sin TOTP confirmado. Va al final por dos
    # precondiciones de orden: necesita 'request.user.is_verified()' de
    # OTPMiddleware y usa 'messages.warning', cuyo almacenamiento solo lo
    # inicializa MessageMiddleware. Ubicarlo antes de MessageMiddleware rompe
    # el aviso con MessageFailure (evidencia: 2 tests fallidos), por eso no
    # queda pegado a OTPMiddleware pese a ser su dependencia más directa.
    'app_quimico.middleware.ForceMFAAdminMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='gestor_quimico_bd'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# HTTPS and security headers
# These default to development-safe values; production sets them via env.
# https://docs.djangoproject.com/en/5.2/topics/security/

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# Login rate limiting (django-axes): lockout after repeated failures.

AXES_ENABLED = config('AXES_ENABLED', default=True, cast=bool)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours

# Email (recuperación de contraseña)
# https://docs.djangoproject.com/en/5.2/topics/email/
# Desarrollo: backend de consola, el correo de recuperación se imprime en la
# terminal. Simulación de producción: definir EMAIL_HOST para usar SMTP.
# Producción en PythonAnywhere free: los web apps no pueden abrir SMTP saliente
# (el proxy solo publica HTTP(S) de la lista blanca, y api.brevo.com está en
# ella), así que definir EMAIL_API_KEY envía por la API HTTP de Brevo.
# Prioridad del default: EMAIL_API_KEY > EMAIL_HOST > consola. Un EMAIL_BACKEND
# explícito en el entorno siempre gana. Las credenciales siempre vienen del
# entorno, nunca del código (ver .env.example).

EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)

# API key de Brevo (panel: SMTP & API -> API Keys). Vacía = no se usa la API.
EMAIL_API_KEY = config('EMAIL_API_KEY', default='')

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='Gestor Químico <no-reply@gestorquimico.local>'
)

# Display name used in user-facing emails (password reset subject/body).
# Kept independent from django.contrib.sites so the branded name does not
# depend on the request host.
SITE_DISPLAY_NAME = config('SITE_DISPLAY_NAME', default='Gestor Químico')

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'app_quimico.brevo_api_backend.BrevoApiEmailBackend'
        if EMAIL_API_KEY
        else (
            'django.core.mail.backends.smtp.EmailBackend'
            if EMAIL_HOST
            else 'django.core.mail.backends.console.EmailBackend'
        )
    ),
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URLs Autenticación de Django
LOGIN_URL = 'login' # Nombre de la URL para redirigir si se requiere login
LOGIN_REDIRECT_URL = 'perfil_personal' # URL a la que ir tras un login exitoso (ej. perfil)
LOGOUT_REDIRECT_URL = 'home' # URL a la que ir tras un logout exitoso (ej. home)
