# Generated by Django 5.2.8 on 2025-11-24 04:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_elemento', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Elemento')),
                ('simbolo_elemento', models.CharField(max_length=3, unique=True, verbose_name='Símbolo')),
                ('numero_atomico_elemento', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='El Número Atómico (Z) debe ser mayor que cero (1 o superior)'), django.core.validators.MaxValueValidator(118, message='El valor máximo permitido es 118.')], verbose_name='Número Atómico (Z)')),
                ('peso_atomico_elemento', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1.0070'), message='El valor mínimo es 1.0070 g/mol (Hidrógeno)'), django.core.validators.MaxValueValidator(Decimal('294.0000'), message='El valor máximo es 294 g/mol.')], verbose_name='Peso Atómico')),
            ],
            options={
                'verbose_name': 'Elemento Químico',
                'verbose_name_plural': 'Elementos Químicos',
            },
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_industria', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Industria')),
            ],
            options={
                'verbose_name': 'Industria',
                'verbose_name_plural': 'Industrias',
            },
        ),
        migrations.CreateModel(
            name='CompuestoQuimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compuesto', models.CharField(max_length=255, verbose_name='Nombre del Compuesto')),
                ('formula_compuesto', models.CharField(max_length=255, unique=True, verbose_name='Fórmula Química')),
                ('peso_molecular_compuesto', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Peso Molecular')),
                ('fecha_registro_compuesto', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compuestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_industria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_quimico.industria', verbose_name='Tipo de Industria')),
            ],
            options={
                'verbose_name': 'Compuesto Químico',
                'verbose_name_plural': 'Compuestos Químicos',
            },
        ),
        migrations.CreateModel(
            name='DetalleElemento',
            fields=[
                ('id_elemento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_quimico.elementoquimico', verbose_name='Elemento Químico')),
                ('grupo_elemento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Grupo')),
                ('periodo_elemento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Periodo')),
                ('categoria_elemento', models.CharField(choices=[('Metales', 'Metales'), ('No Metales', 'No Metales'), ('Alcalinos', 'Alcalinos'), ('Alcalinos-térreos', 'Alcalinos-térreos'), ('Lantánidos', 'Lantánidos'), ('Actínidos', 'Actínidos'), ('Metales de Transición', 'Metales de Transición'), ('Otros Metales', 'Otros Metales'), ('Metaloides', 'Metaloides'), ('Otros No Metales', 'Otros No Metales'), ('Halógenos', 'Halógenos'), ('Gases Nobles', 'Gases Nobles')], max_length=50, verbose_name='Categoría')),
                ('electronegatividad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.70'), message='El valor mínimo es 0.70 (Francio)'), django.core.validators.MaxValueValidator(Decimal('4.00'), message='El valor máximo es 4.00 (Flúor)')])),
                ('afinidad_electronica', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-348.00'), message='El valor mínimo es -348.00 kJ/mol (Cloro)'), django.core.validators.MaxValueValidator(Decimal('-0.0001'), message='El valor máximo debe ser estrictamente negativo')], verbose_name='Afinidad Electrónica')),
                ('energia_de_ionizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('382.70'), message='El valor mínimo es 382.70 kJ/mol (Cesio)'), django.core.validators.MaxValueValidator(Decimal('2372.30'), message='El valor máximo es 2372.30 kJ/mol (Helio)')], verbose_name='Energía de Ionización')),
                ('radio_covalente', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.32'), message='El valor mínimo es 0.32 Å.'), django.core.validators.MaxValueValidator(Decimal('2.98'), message='El valor máximo es 2.98 Å.')], verbose_name='Radio Covalente')),
                ('descripcion_elemento', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Detalle del Elemento',
                'verbose_name_plural': 'Detalles de Elementos',
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_uso', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Uso/Aplicación')),
                ('id_industria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_quimico.industria', verbose_name='Industria')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
            },
        ),
        migrations.CreateModel(
            name='CompuestoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion_minima', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='La concentración mínima debe ser mayor o igual a 0.01')], verbose_name='Concentración Mínima')),
                ('tipo_concentracion', models.CharField(choices=[('%p/p', '% Peso en Peso (p/p)'), ('%p/v', '% Peso en Volumen (p/v)'), ('ppm', 'Partes por Millón (ppm)'), ('[M]', 'Molaridad [M]'), ('[N]', 'Normalidad [N]'), ('otra', 'Otra Unidad')], default='%p/p', max_length=5, verbose_name='Tipo de Concentración')),
                ('id_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.aplicacion', verbose_name='Aplicación')),
                ('id_compuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.compuestoquimico', verbose_name='Compuesto')),
            ],
            options={
                'verbose_name': 'Compuesto en Aplicación',
                'verbose_name_plural': 'Compuestos en Aplicaciones',
                'unique_together': {('id_compuesto', 'id_aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='ElementoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_uso', models.CharField(max_length=255, verbose_name='Notas de Uso')),
                ('id_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.aplicacion', verbose_name='Aplicación')),
                ('id_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.elementoquimico', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Elemento en Aplicación',
                'verbose_name_plural': 'Elementos en Aplicaciones',
                'unique_together': {('id_elemento', 'id_aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='ElementoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_elem_en_comp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('id_compuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.compuestoquimico', verbose_name='Compuesto')),
                ('id_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quimico.elementoquimico', verbose_name='Elemento')),
            ],
            options={
                'verbose_name': 'Elemento en Compuesto',
                'verbose_name_plural': 'Elementos en Compuestos',
                'unique_together': {('id_elemento', 'id_compuesto')},
            },
        ),
    ]
