# Generated by Django 5.2.8 on 2025-11-24 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compuestoquimico',
            name='formula_compuesto',
            field=models.CharField(max_length=255, verbose_name='Fórmula Química'),
        ),
        migrations.AddConstraint(
            model_name='compuestoquimico',
            constraint=models.UniqueConstraint(fields=('formula_compuesto', 'usuario'), name='unique_formula_per_user'),
        ),
    ]
