# Generated by Django 5.2.8 on 2026-09-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0003_setup_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compuestoaplicacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='elementoaplicacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='elementocompuesto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='compuestoaplicacion',
            constraint=models.UniqueConstraint(fields=('id_compuesto', 'id_aplicacion'), name='unique_compuesto_por_aplicacion'),
        ),
        migrations.AddConstraint(
            model_name='elementoaplicacion',
            constraint=models.UniqueConstraint(fields=('id_elemento', 'id_aplicacion'), name='unique_elemento_por_aplicacion'),
        ),
        migrations.AddConstraint(
            model_name='elementocompuesto',
            constraint=models.UniqueConstraint(fields=('id_elemento', 'id_compuesto'), name='unique_elemento_por_compuesto'),
        ),
    ]
