# Generated by Django 5.2.8 on 2026-09-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0004_alter_compuestoaplicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compuestoquimico',
            name='fecha_registro_compuesto',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
