# Generated by Django 5.2.8 on 2026-09-19 03:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0005_alter_compuestoquimico_fecha_registro_compuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleelemento',
            name='afinidad_electronica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-348.60'), message='El valor mínimo es -348.60 kJ/mol (Cloro)'), django.core.validators.MaxValueValidator(Decimal('-0.0001'), message='El valor máximo debe ser estrictamente negativo')], verbose_name='Afinidad Electrónica'),
        ),
        migrations.AlterField(
            model_name='detalleelemento',
            name='energia_de_ionizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('375.70'), message='El valor mínimo es 375.70 kJ/mol (Cesio)'), django.core.validators.MaxValueValidator(Decimal('2372.30'), message='El valor máximo es 2372.30 kJ/mol (Helio)')], verbose_name='Energía de Ionización'),
        ),
    ]
