# Generated by Django 5.2.8 on 2026-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0009_seed_administradores_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='compuestoquimico',
            name='smiles',
            field=models.TextField(blank=True, help_text='Notación SMILES opcional para mostrar la estructura 2D', null=True, verbose_name='Estructura SMILES'),
        ),
    ]
