# Generated by Django 5.2.8 on 2026-09-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0010_compuestoquimico_smiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleelemento',
            name='categoria_elemento',
            field=models.CharField(choices=[('No Metales', 'No Metales'), ('Alcalinos', 'Alcalinos'), ('Alcalinos-térreos', 'Alcalinos-térreos'), ('Lantánidos', 'Lantánidos'), ('Actínidos', 'Actínidos'), ('Metales de Transición', 'Metales de Transición'), ('Otros Metales', 'Otros Metales'), ('Metaloides', 'Metaloides'), ('Halógenos', 'Halógenos'), ('Gases Nobles', 'Gases Nobles')], max_length=50, verbose_name='Categoría'),
        ),
    ]
