# Generated by Django 5.2.8 on 2026-09-25 03:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quimico', '0011_alter_detalleelemento_categoria_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleelemento',
            name='radio_covalente',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('28'), message='El valor mínimo es 28 pm.'), django.core.validators.MaxValueValidator(Decimal('350'), message='El valor máximo es 350 pm.')], verbose_name='Radio Covalente'),
        ),
    ]
